global:
  scrape_interval: 1s
  evaluation_interval: 5s
scrape_configs:
  - job_name: compute-job
    static_configs:
      - targets: ["compute-node-0:2487","compute-node-1:2487"]

  - job_name: meta-job
    static_configs:
      - targets: ["meta-node-0:2487"]

  - job_name: minio-job
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ["minio-0:3253"]

  - job_name: compactor-job
    static_configs:
      - targets: ["compactor-0:2487"]

  - job_name: etcd
    static_configs:
      - targets: ["etcd:2379"]