global:
  scrape_interval: 1s
  evaluation_interval: 5s
scrape_configs:
  - job_name: compute-job
    static_configs:
      - targets: ["localhost:2487","localhost:2488"]

  - job_name: meta-job
    static_configs:
      - targets: ["localhost:2489"]

  - job_name: minio-job
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ["localhost:3253"]

  - job_name: compactor-job
    static_configs:
      - targets: ["localhost:2490"]

  - job_name: etcd
    static_configs:
      - targets: ["localhost:2379"]